meta_product_name: "Energywatch"
meta_title: "Energywatch – Smart energy starts with you."
meta_description: "When it comes to energy, timing is everything."
meta_image: "fb-banner.jpg“" # should exist in `app/assets/images/`
